// Lessons

const hsk1_lessons = [
  {
    id: "hsk1_l1",
    hsk_level: "HSK1",
    lesson_number: 1,
    title_ru: "Приветствие и знакомство",
    character_ids: [],
  },
  {
    id: "hsk1_l2",
    hsk_level: "HSK1",
    lesson_number: 2,
    title_ru: "Как тебя зовут",
    character_ids: [],
  },
  {
    id: "hsk1_l3",
    hsk_level: "HSK1",
    lesson_number: 3,
    title_ru: "Прядставляем других",
    character_ids: [],
  },
  {
    id: "hsk1_l4",
    hsk_level: "HSK1",
    lesson_number: 4,
    title_ru: "Моя семья. Номера.",
    character_ids: [],
  },
  {
    id: "hsk1_l5",
    hsk_level: "HSK1",
    lesson_number: 5,
    title_ru: "Я могу. Описываем вещи.",
    character_ids: [],
  },
  {
    id: "hsk1_l6",
    hsk_level: "HSK1",
    lesson_number: 6,
    title_ru: "Даты",
    character_ids: [],
  },
  {
    id: "hsk1_l7",
    hsk_level: "HSK1",
    lesson_number: 7,
    title_ru: "Описываем желания",
    character_ids: [],
  },
  {
    id: "hsk1_l8",
    hsk_level: "HSK1",
    lesson_number: 8,
    title_ru: "Работа и карьера",
    character_ids: [],
  },
  {
    id: "hsk1_l9",
    hsk_level: "HSK1",
    lesson_number: 9,
    title_ru: "Вежливые вопросы",
    character_ids: [],
  },
  {
    id: "hsk1_l10",
    hsk_level: "HSK1",
    lesson_number: 10,
    title_ru: "Который час?",
    character_ids: [],
  },
  {
    id: "hsk1_l11",
    hsk_level: "HSK1",
    lesson_number: 11,
    title_ru: "Погода",
    character_ids: [],
  },
  {
    id: "hsk1_l12",
    hsk_level: "HSK1",
    lesson_number: 12,
    title_ru: "Смотрим телевизор",
    character_ids: [],
  },
  {
    id: "hsk1_l13",
    hsk_level: "HSK1",
    lesson_number: 13,
    title_ru: "Говорим о прошлом 1",
    character_ids: [],
  },
  {
    id: "hsk1_l14",
    hsk_level: "HSK1",
    lesson_number: 14,
    title_ru: "Говорим о прошлом 2",
    character_ids: [],
  },
];

// Characters

const hsk1_characters = [
  {
    id: "hsk1_l1_ch001",
    character: "再见",
    pinyin: ["zàijiàn"],
    translation: ["До свидания"],
  },
  {
    id: "hsk1_l1_ch002",
    character: "你好",
    pinyin: ["nǐ hǎo"],
    translation: ["Здравствуйте"],
  },
  {
    id: "hsk1_l1_ch003",
    character: "谢谢",
    pinyin: ["xièxiè"],
    translation: ["Спасибо"],
  },
  {
    id: "hsk1_l1_ch004",
    character: "对不起",
    pinyin: ["duìbùqǐ"],
    translation: ["Простите"],
  },
  {
    id: "hsk1_l1_ch005",
    character: "没关系",
    pinyin: ["méiguān xì"],
    translation: ["Нет проблем"],
  },
  {
    id: "hsk1_l1_ch006",
    character: "不谢",
    pinyin: ["bùxiè"],
    translation: ["Нет проблем"],
  },
  {
    id: "hsk1_l1_ch007",
    character: "不客气",
    pinyin: ["bù kèqì"],
    translation: ["Пожалуйста"],
  },
  {
    id: "hsk1_l1_ch008",
    character: "我",
    pinyin: ["wǒ"],
    translation: ["я"],
  },
  {
    id: "hsk1_l1_ch009",
    character: "你",
    pinyin: ["nǐ"],
    translation: ["ты"],
  },
  {
    id: "hsk1_l1_ch010",
    character: "他",
    pinyin: ["tā"],
    translation: ["он, она, это"],
  },
  {
    id: "hsk1_l2_ch011",
    character: "人",
    pinyin: ["rén"],
    translation: ["Человек"],
  },
  {
    id: "hsk1_l2_ch012",
    character: "国",
    pinyin: ["guó"],
    translation: ["Страна"],
  },
  {
    id: "hsk1_l2_ch013",
    character: "中国",
    pinyin: ["zhōng guó"],
    translation: ["Китай"],
  },
  {
    id: "hsk1_l2_ch014",
    character: "学生",
    pinyin: ["xué sheng"],
    translation: ["Студент"],
  },
  {
    id: "hsk1_l2_ch015",
    character: "是",
    pinyin: ["shì"],
    translation: ["есть"],
  },
  {
    id: "hsk1_l2_ch016",
    character: "吗",
    pinyin: ["ma"],
    translation: ["вопросительный вопрос"],
  },
  {
    id: "hsk1_l2_ch017",
    character: "老师",
    pinyin: ["lǎo shī"],
    translation: ["Учитель"],
  },
  {
    id: "hsk1_l2_ch018",
    character: "叫",
    pinyin: ["jiào"],
    translation: ["Звать"],
  },
  {
    id: "hsk1_l2_ch019",
    character: "什么",
    pinyin: ["shén me"],
    translation: ["Как, что"],
  },
  {
    id: "hsk1_l2_ch020",
    character: "名字",
    pinyin: ["míng zi"],
    translation: ["Имя"],
  },
  {
    id: "hsk1_l3_ch021",
    character: "汉语",
    pinyin: ["hàn yǔ"],
    translation: ["Китайский"],
  },
  {
    id: "hsk1_l3_ch022",
    character: "哪",
    pinyin: ["nǎ"],
    translation: ["какой, кто"],
  },
  {
    id: "hsk1_l3_ch023",
    character: "谁",
    pinyin: ["shéi"],
    translation: ["кто"],
  },
  {
    id: "hsk1_l3_ch024",
    character: "同学",
    pinyin: ["tóng xué"],
    translation: ["одноклассник"],
  },
  {
    id: "hsk1_l3_ch025",
    character: "朋友",
    pinyin: ["péng yǒu"],
    translation: ["друг"],
  },
  {
    id: "hsk1_l3_ch026",
    character: "的",
    pinyin: ["de"],
    translation: ["частица принадлежности"],
  },
  {
    id: "hsk1_l3_ch027",
    character: "呢",
    pinyin: ["ne"],
    translation: ["вопросительная частица"],
  },
  {
    id: "hsk1_l4_ch028",
    character: "零 ",
    pinyin: ["líng"],
    translation: ["ноль"],
  },
  {
    id: "hsk1_l4_ch029",
    character: "一",
    pinyin: ["yī"],
    translation: ["один"],
  },
  {
    id: "hsk1_l4_ch030",
    character: "二",
    pinyin: ["èr"],
    translation: ["два"],
  },
  {
    id: "hsk1_l4_ch031",
    character: "三",
    pinyin: ["sān"],
    translation: ["три"],
  },
  {
    id: "hsk1_l4_ch032",
    character: "四",
    pinyin: ["sì"],
    translation: ["четыри"],
  },
  {
    id: "hsk1_l4_ch033",
    character: "五",
    pinyin: ["wǔ"],
    translation: ["пять"],
  },
  {
    id: "hsk1_l4_ch034",
    character: "六",
    pinyin: ["liù"],
    translation: ["шесть"],
  },
  {
    id: "hsk1_l4_ch035",
    character: "七",
    pinyin: ["qī"],
    translation: ["семь"],
  },
  {
    id: "hsk1_l4_ch036",
    character: "八",
    pinyin: ["bā"],
    translation: ["восемь"],
  },
  {
    id: "hsk1_l4_ch037",
    character: "九",
    pinyin: ["jiǔ"],
    translation: ["девять"],
  },
  {
    id: "hsk1_l4_ch038",
    character: "十",
    pinyin: ["shí"],
    translation: ["десять"],
  },
  {
    id: "hsk1_l4_ch039",
    character: "电话",
    pinyin: ["diàn huà"],
    translation: ["номер телефона"],
  },
  {
    id: "hsk1_l4_ch040",
    character: "多少",
    pinyin: ["duō shǎo"],
    translation: ["сколько"],
  },
  {
    id: "hsk1_l4_ch041",
    character: "口",
    pinyin: ["kǒu"],
    translation: ["количественная частица"],
  },
  {
    id: "hsk1_l4_ch042",
    character: "家",
    pinyin: ["jiā"],
    translation: ["семья"],
  },
  {
    id: "hsk1_l4_ch043",
    character: "女儿",
    pinyin: ["nǚ ér"],
    translation: ["дочь"],
  },
  {
    id: "hsk1_l4_ch044",
    character: "有",
    pinyin: ["yǒu"],
    translation: ["иметь"],
  },
  {
    id: "hsk1_l4_ch045",
    character: "几",
    pinyin: ["jǐ"],
    translation: ["сколько"],
  },
  {
    id: "hsk1_l4_ch046",
    character: "岁",
    pinyin: ["suì"],
    translation: ["лет "],
  },
  {
    id: "hsk1_l4_ch047",
    character: "今年",
    pinyin: ["jīn nián"],
    translation: ["этот год"],
  },
  {
    id: "hsk1_l4_ch048",
    character: "多",
    pinyin: ["duō"],
    translation: ["сколько"],
  },
  {
    id: "hsk1_l4_ch049",
    character: "大",
    pinyin: ["dà"],
    translation: ["большой"],
  },
  {
    id: "hsk1_l4_ch050",
    character: "了",
    pinyin: ["le"],
    translation: ["частица изменения"],
  },
  {
    id: "hsk1_l5_ch051",
    character: "会",
    pinyin: ["huì"],
    translation: ["могу, умею"],
  },
  {
    id: "hsk1_l5_ch052",
    character: "说",
    pinyin: ["shuō"],
    translation: ["говорить"],
  },
  {
    id: "hsk1_l5_ch053",
    character: "写",
    pinyin: ["xiě"],
    translation: ["писать"],
  },
  {
    id: "hsk1_l5_ch054",
    character: "读",
    pinyin: ["dú"],
    translation: ["читать"],
  },
  {
    id: "hsk1_l5_ch055",
    character: "汉字",
    pinyin: ["hàn zì"],
    translation: ["Китайские иероглифы"],
  },
  {
    id: "hsk1_l5_ch056",
    character: "做",
    pinyin: ["zuò "],
    translation: ["делать, готовить, производить"],
  },
  {
    id: "hsk1_l5_ch057",
    character: "妈妈",
    pinyin: ["mā ma"],
    translation: ["мама"],
  },
  {
    id: "hsk1_l5_ch058",
    character: "菜",
    pinyin: ["cài"],
    translation: ["блюдо"],
  },
  {
    id: "hsk1_l5_ch059",
    character: "怎么",
    pinyin: ["zěn me "],
    translation: ["как"],
  },
  {
    id: "hsk1_l5_ch060",
    character: "这个",
    pinyin: ["zhè gè"],
    translation: ["это"],
  },
];
